/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.ManejoArchivos;
import Clases.Usuarios;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Josué
 */
public class RegistrarUsuario extends javax.swing.JFrame {

    private ArrayList<Usuarios> listausuarios;
    private ManejoArchivos ma;

    /**
     * Creates new form RegistrarUsuario
     */
    public RegistrarUsuario() {
        initComponents();
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.setBounds((ancho / 2) - (this.getWidth() / 2), (alto / 2) - (this.getHeight() / 2), 1080, 720);
        listausuarios = new ArrayList<>();
        ma = new ManejoArchivos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regresar.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 590, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CR.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 590, -1, -1));

        jTextField1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 430, 40));

        jPasswordField2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        getContentPane().add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, 430, 40));

        jPasswordField1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, 430, 40));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Confirmar Contraseña");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Contraseña");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Usuario");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 52)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Registrar usuario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 440, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoD.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        IniciarSesion is = new IniciarSesion();
        this.dispose();
        is.setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked
    /* private void miUsuario(){
        Usuarios yo = new Usuarios();
        yo.setNombre("Quiubo");
        yo.setContraseña("Hola");
       
        listausuarios.add(yo);
        ma.serializarUsuario(listausuarios);
        
    }*/
    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        Usuarios user = new Usuarios();
        boolean flag = false;
        boolean existente = false;
        boolean bandera = true;
        if (ma.deserializarUsuario() != null) {
            listausuarios = ma.deserializarUsuario();
            flag = true;
        }

        char[] contra = jPasswordField1.getPassword();
        char[] concontra = jPasswordField2.getPassword();
        String contrasena = new String(contra);
        String concontrasena = new String(concontra);

        //boolean flag = false;
        if (jTextField1.getText().isEmpty() || contrasena.isEmpty() || concontrasena.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, verifique que todos los campos hayan sido llenados correctamente");
        } else if (contrasena.equals(concontrasena) && flag == true) {
            int s = listausuarios.size();

            // for (int i = 0; i < s - 1; i++) {
            // if ((listausuarios.get(i).getNombre()).equals(jTextField1.getText())) {
            //     existente = true;
            // } else {// if ((listausuarios.get(i).getNombre())!=(jTextField1.getText())){
            //     existente = false;
            //   }
            // }
            for (Usuarios users : listausuarios) {
                if (users.getNombre().equalsIgnoreCase(jTextField1.getText())) {
                    existente = true;
                } else {
                    existente = false;
                }
            }
            if (existente == true) {
                JOptionPane.showMessageDialog(null, "El usuario ingresado ya existe");
            } else if (existente == false) {
                user = new Usuarios(jTextField1.getText(), contrasena);
                listausuarios.add(user);
                ma.serializarUsuario(listausuarios);
                ma.crearCarpetaUsuario(jTextField1.getText());
                ma.crearCarpetas(jTextField1.getText());

                IniciarSesion is = new IniciarSesion();
               // this.dispose();
               // is.setVisible(true);

                try {
                    ma.crearArchivos(jTextField1.getText());
                } catch (IOException ex) {
                    Logger.getLogger(RegistrarUsuario.class.getName()).log(Level.SEVERE, null, ex);
                }

                //IniciarSesion is = new IniciarSesion();
                //this.dispose();
                //is.setVisible(true);
                jTextField1.setText("");
                jPasswordField1.setText("");
                jPasswordField2.setText("");

               
                this.dispose();
                is.setVisible(true);

            }
        } else if (contrasena.equals(concontrasena) && flag == false) {
            user = new Usuarios(jTextField1.getText(), contrasena);
            listausuarios.add(user);
            ma.serializarUsuario(listausuarios);
            //flag = true;
            ma.crearCarpetaUsuario(jTextField1.getText());
            ma.crearCarpetas(jTextField1.getText());
            try {
                ma.crearArchivos(jTextField1.getText());
            } catch (IOException ex) {
                Logger.getLogger(RegistrarUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
            IniciarSesion is = new IniciarSesion();
            this.dispose();
            is.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
